[package]
name = "day17"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "task1"
path = "src/main.rs"

[[bin]]
name = "task2"
path = "src/main2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.3.2"
